### ISSUE TITLE
Status of voice

### ISSUE THREAD

**Issue by HopeBaron** [kordlib/kord#101]
This issue will function as a overview of introducing voice:

- [x] Heart beating
- [x] IP Discovery
- [x] Audio formatting (Lava Player)
- [ ] Resuming
- [ ] UDP connection and audio forwarding to channels

**Comment by HopeBaron** [comment]
The module will be on hold until [ktorio/ktor #1049](https://github.com/ktorio/ktor/issues/1049) gets fixed
Resuming and proper judging on the life-cycle handling would require at least a function UDP socket that's able to forward opus packets. However the current (dirty) code will be pushed to the voice branch and improve the current parts on the go.

**Comment by VapidLinus** [comment]
Will this make it possible to move users to another voice channel, or is that already possible?

**Comment by HopeBaron** [comment]
Hello, This is already possible using `MemberBehavior#edit` where you have the ability to change the voice channel id

**Comment by DRSchlaubi** [comment]
THE ISSUE GOT FIXED WOOOOOOOOOHOOOOOOOOO

**Comment by NyCodeGHG** [comment]
POGGERS

**Comment by HopeBaron** [comment]
The next big thing probably, hopefully I can ship this with minor changes... But we need to reimpelement this from scratch
