### ISSUE TITLE
Exception after receiving DM (kord-core)

### ISSUE THREAD

**Issue by Noituri** [kordlib/kord#123]
The client after receiving message event throws NPE at
`com.gitlab.kordlib.core.gateway.handler.MessageEventHandler.handle(MessageEventHandler.kt:57)`

From what I checked, `guildId.value!!` might be the cause as guildID is not returned in DMs.

**Comment by BartArys** [comment]
Thanks for reporting this!

The actual problem is Line 56 `guildId is OptionalSnowflake.Missing`, which should compare against `OptionalSnowflake.Value`.

**Comment by Noituri** [comment]
Ah yeah, I totally missed that line

**Comment by BartArys** [comment]
Fixed in 0.7.0-RC
