### ISSUE TITLE
Allow channelId to be null for voice disconnects

### ISSUE THREAD

**Issue by MeLike2D** [kordlib/kord#148]
https://github.com/kordlib/kord/blob/c6911b5c08905bfbb225b70cf25b4438f2748e89/gateway/src/main/kotlin/Command.kt#L188

**Comment by HopeBaron** [comment]
Hello
We are aware of the issue and I've already made a PR to fix it, but it's delayed due to slash commands

**Comment by MeLike2D** [comment]
> Hello
> We are aware of the issue and I've already made a PR to fix it, but it's delayed due to slash commands

Oh okay! Do you have any idea when you think it'll be merged?

**Comment by HopeBaron** [comment]
We are in the last stage of developing Slash commands, so shortly I believe.

**Comment by MeLike2D** [comment]
Alright thanks
