### ISSUE TITLE
Lack of String representation of core entities

### ISSUE THREAD

**Issue by HopeBaron** [kordlib/kord#15]
Core entities must be able to be represented in a string.

If you want to send an entity in a string you will have to do this manually using [formats provided by discord](https://discord.com/developers/docs/reference#message-formatting-formats).
e.g: 
```kotlin
// MessageCreateEvent 
val emoji = getGuild()?.getEmoji(...)
val stringToReply = "This is an <:$name:$id>"
```

We might override the toString() functions of the entity classes so that the user can achieve something like 

```kotlin
// MessageCreateEvent 
val emoji = getGuild()?.getEmoji(...)
val stringToReply = "This is an $emoji"
```

**Comment by BartArys** [comment]
While I appreciate the idea, we should not encourage to usage of `toString` for UI-facing code. That function should be exclusively used for logs and debugging.

**Comment by HopeBaron** [comment]
Fine then we are going to add it to a separate property.
