### ISSUE TITLE
Artifacts aren't deployed to maven central repository?

### ISSUE THREAD

**Issue by mirror-kt** [kordlib/kord#182]
jcenter will got EOL at May, 1st, 2021(https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

A badge in README was replaced from jcenter to maven central in [`40fa27e` (#159)](https://github.com/kordlib/kord/pull/159/commits/40fa27eddd12d1fbc12ba4c89cb8a284d9a94c5f), but artifacts are not found in maven central(https://search.maven.org/search?q=dev.kord).

Coult you deploy the artifacts to maven central?

**Comment by HopeBaron** [comment]
We moved to maven central since 0.7.0. However, we don't have official releases to maven yet, only snapshots.
The 0.7.x branch has a readme that includes the snapshots repository in it that you must include
use `0.7.0-SNAPSHOT` as the version for Kord.

**Comment by mirror-kt** [comment]
I see, thanks you!
