### ISSUE TITLE
"DiscordInteractionGuildMember" is missing "pending" and "is_pending" flags

### ISSUE THREAD

**Issue by MrPowerGamerBR** [kordlib/kord#191]
```json
{"channel_id":"513405772911345664","data":{"id":"812846584084955136","name":"online"},"guild_id":"268353819409252352","id":"814909719054647316","member":{"deaf":false,"is_pending":false,"joined_at":"2017-01-10T12:22:16.323000+00:00","mute":false,"nick":null,"pending":false,"permissions":"4294967295","premium_since":null,"roles":["297051132793061378","334711955736625185","401353261266763778","650869752524439563","693210200496144424"],"user":{"avatar":"8bd2b747f135c65fd2da873c34ba485c","discriminator":"4185","id":"123170274651668480","public_flags":131712,"username":"MrPowerGamerBR"}},"token":"-","type":2,"version":1}
```

~~I have no idea why there are both flags, but they are there when receiving a Discord Interaction.~~

[`is_pending` is being deprecated](https://github.com/discord/discord-api-docs/pull/2299#issuecomment-742773209)

**Comment by DRSchlaubi** [comment]
Funfact: discord includes both fields in the example: https://discord.com/developers/docs/interactions/slash-commands#receiving-an-interaction. But the [Member Object](https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure) only shows pending

**Comment by DRSchlaubi** [comment]
I guess this needs to wait for #192 and #190 to avoid conflicts
