### ISSUE TITLE
Builders/Transformers List

### ISSUE THREAD

**Issue by HopeBaron** [kordlib/kord#209]
This is a reminder to add missing higher order functions for rest module and embed request transformers (Embed -> EmbedRequest)

**Comment by DRSchlaubi** [comment]
There are probably more transformers needed than just embed right?

**Comment by HopeBaron** [comment]
That's a sure thing. that's why the issue is made. List anything you feel that it needs a builder or a transformer here

**Comment by gdude2002** [comment]
I'd like to be able to subclass some entities as well as replacing them in some events and such.

My use-case is basically for people that make use of PluralKit, which is basically an accessibility tool for people that are plural - it allows every member of a plural system to interact separately by deleting messages from the account and resending them as webhook messages.

I'd like to be able to add this metadata to events and entities, based on extensions to my framework. This means that subclassing is vital, as the extra context may not always be available, and the extension may not always be loaded.

**Comment by HopeBaron** [comment]
Closed as this idea doesn't really solve the issue at hand
