### ISSUE TITLE
`isImage` check for Attachment is inaccurate

### ISSUE THREAD

**Issue by qbosst** [kordlib/kord#317]
For Attachments, there is an `isImage` attribute that checks whether the attachment is an image by making sure the width and height of the image is not null, as per the [Discord Docs](https://discord.com/developers/docs/resources/channel#attachment-object-attachment-structure).
![image](https://user-images.githubusercontent.com/60557521/121945484-bce07500-cd4b-11eb-9340-dfaa9047fd65.png)

However, as usual, the Discord Docs are outdated/wrong and video attachments can also provide a height and width, making `isImage` inaccurate, as it will return true for when videos are sent.

JDA overcomes this by checking the file extension of the attachment, I was wondering if you could do something similar?

**Comment by BartArys** [comment]
I'm not really sure where to go with this function. `isImage` is a misnomer, Discord only renders a [select few image types](https://discord.com/developers/docs/reference#image-formatting-image-formats), it doesn't work on others like `.tiff` and `.svg`.

If this is supposed to return true on all image types, it should do so irrespective of the width and height field. If however it should only return true for rendered images, we should add an extra predicate for the types Discord supports, and change the name.

**Comment by HopeBaron** [comment]
This should be fixed as we replaced the isImage implementation to check the file extension.
Please re-open if there any other concerns
