### ISSUE TITLE
KTOR outputs warning (but no trace), login never completes

### ISSUE THREAD

**Issue by tlitookilakin** [kordlib/kord#345]
Calling Kord.login() prints this warning to console-
`[DefaultDispatcher-worker-2] WARN io.ktor.util.random - NativePRNGNonBlocking is not found, fallback to SHA1PRNG`
and execution hangs. 

Changing ktor to use DRBG removes the warning, but execution still hangs.

**Comment by BartArys** [comment]
This is by design: https://github.com/kordlib/kord/blob/0.7.x/core/src/main/kotlin/Kord.kt#L123-L125

The login method suspends until the gateway closes.

**Comment by tlitookilakin** [comment]
Hmmm, I think I misunderstood the program flow here. Sorry for the trouble.
