### ISSUE TITLE
Video embed field not accessible from builder?

### ISSUE THREAD

**Issue by BenjaminHolland** [kordlib/kord#364]
Is there a reason for this?

**Comment by HopeBaron** [comment]
Hello there!
The reason is that it can't be set

> For the embed object, you can set every field except type (it will be rich regardless of if you try to set it), provider, video, and any height, width, or proxy_url values for images.

https://discord.com/developers/docs/resources/channel#create-message-limitations

**Comment by BenjaminHolland** [comment]
👍
