### ISSUE TITLE
User Commands and Message Commands

### ISSUE THREAD

**Issue by Luewd** [kordlib/kord#365]
Discord has added new features that allow you to add custom right click actions for right clicking on users and/or messages.
They're a new type of Application Command so they are similar to Slash Commands in implementation.

See [User Command Docs](https://discord.com/developers/docs/interactions/application-commands#user-commands) and scroll down to see the docs for Message Commands.

**Comment by HopeBaron** [comment]
Hello luewd, the contexts are already being worked on, you can try out a snapshot using `contexts-SNAPSHOT`
branch: https://github.com/kordlib/kord/tree/contexts
