### ISSUE TITLE
Missing `attachments` for message/webhook edit

### ISSUE THREAD

**Issue by MrPowerGamerBR** [kordlib/kord#372]
The `attachments` field can be used to keep already existing attachments in a message, I guess that because Kord never uses that field, all attachments in the message are kept.

https://discord.com/developers/docs/resources/channel#edit-message
https://discord.com/developers/docs/resources/webhook#edit-webhook-message

**Comment by HopeBaron** [comment]
Not all messages are the same. Ephemeral messages can't have files.

**Comment by MrPowerGamerBR** [comment]
> 
> 
> Not all messages are the same. Ephemeral messages can't have files.

Yes... but I'm not talking about file upload, I'm talking about removing files from an existing message

From the docs

attachments | array of attachment objects | attached files to keep
-- | -- | --

Unless if I'm blind, [Kord doesn't seem to support this](https://github.com/kordlib/kord/blob/0.8.x/rest/src/main/kotlin/builder/message/modify/PublicFollowupMessageModifyBuilder.kt), you can attach *new* files to a message, sure, but you can't remove attachments from an existing message.

I may be misunderstanding what the `attachments` field does, but it would still be missing from Kord anyways.

**Comment by HopeBaron** [comment]
attachments are files on your side.
Discord attaches meta data to these files and call them attachements

https://github.com/kordlib/kord/blob/0.8.x/rest/src/main/kotlin/builder/message/modify/PublicFollowupMessageModifyBuilder.kt#L24

**Comment by MrPowerGamerBR** [comment]
> 
> 
> attachments are files on your side.
> Discord attaches meta data to these files and call them attachements
> 
> [files field](https://github.com/kordlib/kord/blob/0.8.x/rest/src/main/kotlin/builder/message/modify/PublicFollowupMessageModifyBuilder.kt#L24)

The files field is used for file upload, sure, this makes sense and it does work.

But if you are editing a message (via webhooks or a normal message) you can also *remove* files already uploaded to it, so, what I can do is: Send a message with a "image.png" file and then later edit the message by uploading a "image.gif" file to it, and using the `attachments` field to remove the original "image.png" file.

Currently with Kord, while you can add new files to an already existing message, you can't *remove* the original image from the message.

Of course, I may be misunderstanding what the Discord documentation says, but "attached files to keep" seems to be that it can be used to remove files from an existing message, and the `attachments` field doesn't exist on the create message endpoint, which further makes me think that this can be used to remove attachments from a message.

**Comment by HopeBaron** [comment]
just provide an empty list for the `files` and it will remove the files.
null acts as no-op in our modify builders.

**Comment by MrPowerGamerBR** [comment]
> 
> 
> just provide an empty list for the `files` and it will remove the files.
> null acts as no-op in our modify builders.

That's what I did, and it didn't work :sob:

Probably because setting an empty list just clears the `file` field (so it removes any file that was going to be uploaded), it doesn't change anything in the `attachments` field because Kord doesn't use it.
