### ISSUE TITLE
`ThreadParentChannelBehavior.getPublicArchivedThreads` has issues with caching

### ISSUE THREAD

**Issue by Blacklands** [kordlib/kord#383]
As stated [here](https://github.com/kordlib/kord/blob/1f5d8073b11ce00ad21ca910ab867a8563cbaeeb/core/src/main/kotlin/behavior/channel/threads/ThreadParentChannelBehavior.kt#L40-L41), this method should return the threads in a specific order: By their archive timestamp, descending.

While this works the first time when calling the method for a given channel, calling it a second time will return the threads in a different order that appears to be random.

This is because when caching for channels is enabled (which it is by default), on the JVM a `ConcurrentHashMap` is used (according to [the wiki](https://github.com/kordlib/kord/wiki/Caching)), which does not keep the insertion order of its elements. So, the archive timestamp ordering is lost, and any subsequent calls of the method that use this cache will return a wrong order.

So, I think either

- the documentation of the method would need to be changed (since it does not honor its own contract),
- or the default backing collection for caches on the JVM would need to be changed into something that preserves its insertion order - although I'm not sure if there is any collection in the standard library that does and still works well in a highly concurrent environment

I know I can just disable caching for channels, at least for now, but ultimately I think it should be possible to have both the current (documented) behavior of the method kept, and also it working correctly with channel caching.
Fetching a lot of archived threads can be expensive, since there can potentially be hundreds or thousands of them for a single channel. Often, one is only interested in the most recently archived ones, so this behavior makes sense for that - but it requires them to actually be delivered in an ordered fashion.

Is there currently an available alternative for channel caching? Does `MapLikeCollection.lruLinkedHashMap` work for channels by default?

**Comment by HopeBaron** [comment]
Hello there @Blacklands, 
Thanks for taking your time to write a detailed issue.

The function's implementation should match the documentation as we allow for combined supplying strategies. thus it would cause inconsistency between the REST behavior and cache as you've already experienced.

if you are looking to change the backing implementation of the cache you may be interested in editing the `cache` builder in Kord as explained in the wiki.

Thanks for brining light to this issue
