### ISSUE TITLE
Ignore PRESENCES_REPLACE event

### ISSUE THREAD

**Issue by BartArys** [kordlib/kord#42]
`PRESENCES_REPLACE` is an event that fires to update the client's friend list. Since bots can't have friends (😔) this event is completely useless, which is proven by the fact that the payload is an empty array.

Why bots receive this event is one of humanity's greatest mysteries. Nonetheless, we should ignore this event moving forward.

**Comment by lukellmann** [comment]
With #923, this event would now no longer be ignored. Instead a `dev.kord.gateway.UnknownDispatchEvent` / `dev.kord.core.event.UnknownEvent` would be created.
