### ISSUE TITLE
Use kotlinx-datetime

### ISSUE THREAD

**Issue by BartArys** [kordlib/kord#43]
The madlads over at Jetbrains just released [another banger library](https://github.com/Kotlin/kotlinx-datetime) that brings Java's DateTime API to kotlin-multiplatform. Since our project's only real remaining dependency on the Java stdlib is the datetime API we can use this to yeet that stuff out of there and then realize that we just imported megabytes of typealiases.  It'll be grand.

Note that kotlinx-datetime does **not** typealias java.time.  As such, we should leave the external API using java time  intact, simply providing kotlin's version as an alternative, and remove java time as an internal dependency.

**Comment by DRSchlaubi** [comment]
There actually is a PR for Kotlin/kotlinx-datetime#56 which is their issue for this bug now: Kotlin/kotlinx-datetime#107
