### ISSUE TITLE
Dokka docs down & Wiki docs nonexistent (404)

### ISSUE THREAD

**Issue by Aisuma** [kordlib/kord#447]
Title says it all 
https://kordlib.github.io/kord/ returns 404 page not found. 
Wiki is empty.
Docs are missing (in action?)

**Comment by HopeBaron** [comment]
Hello there, 
Wiki is not empty, you just probably looked at the first page.
Docs will be regenerated once we add our new features in the next release as the old docs are kinda misleading as lots and lots of classes has been renamed.

**Comment by HopeBaron** [comment]
I took the time to revert to last known successful run for the gh-pages
https://kordlib.github.io/kord/

**Comment by HopeBaron** [comment]
Will be closed, please re-open if you'd like to followup
