### ISSUE TITLE
Stickers list is always empty

### ISSUE THREAD

**Issue by PotatoPresident** [kordlib/kord#453]
[Discord deprecated the `stickers` field in the message object and replaced it with `sticker_items`.](https://discord.com/developers/docs/resources/channel#message-object)

**Comment by HopeBaron** [comment]
I haven't heard from you in this regards
Please checkout https://github.com/kordlib/kord/tree/revamp-stickers branch and give feedback

**Comment by HopeBaron** [comment]
Fix will be delievered in 0.8.0-M9 along the re-write of the stickers
