### ISSUE TITLE
Kord: What's next

### ISSUE THREAD

**Issue by HopeBaron** [kordlib/kord#457]
Hey there!

There are some points I'd like to make clear. Specially that we've made lots of devs lives easier and have seen much of useful and positive impressions in regards to the project. There is no reason for the project to stop in the foreseeable future. However, some points must be cleared out so we can move forward together.

# The projects

I know this has been discussed multiple times and we didn't really take this in, but as Kord stands, it became a large project that neither I nor Bart are able to maintain the pieces of this project, specially with all these changes happening on the Kord side. We might also consider merging them into one modularized repo. So we'd be glad to accept any help offered by the community.

# The developer role

I'll be passing the role to those who've shown interest in the project and made changes that took us one step further.
Surely this won't happen unless you'd like to do so. This will allow us to maintain Kord in a much better way.

# Discussions

New changes or future plans will be discussed with the community in the issues more openly specially that you guys have offered much help, ideas and improvements. (any discussions happening on Discord should be made available here)

Make more issues in GitHub as it's easier to follow up than Discord.

**Comment by DRSchlaubi** [comment]
first

**Comment by Skyslycer** [comment]
Second
