### ISSUE TITLE
Make Idenfify's  largeThreshold configurable, or raise it to 250

### ISSUE THREAD

**Issue by Galarzaa90** [kordlib/kord#460]
It seems like by default, `DefaultGateway` is being used, which has largeThreshold set to `50`: https://github.com/kordlib/kord/blob/62e5744d76520a34d267c370caa675fec520d107/gateway/src/main/kotlin/DefaultGateway.kt#L301-L310

I couldn't find a way to change this using the `KordBuilder`.

Increasing this could aid larger bots in reducing the amount of guilds that need to have their members requested.

I don't know if there would be a drawback in increasing this to `250` by default. But if there is, exposing it so it can be configured would be good.

**Comment by HopeBaron** [comment]
Should be able to specify threshold from gateway configuration now

**Comment by Galarzaa90** [comment]
How can this be set using `KordBuilder`? Since I'm using KordEx, this is the only thing I have to configure Kord (as far as I know)

I see that this is defined from `GatewayConfigurationBuilder` in the `start` extension function of `Gateway`.

**Comment by HopeBaron** [comment]
it's 250 by default as far as the builder implies
