### ISSUE TITLE
Use Kord with App instead of Bot?

### ISSUE THREAD

**Issue by dotCipher** [kordlib/kord#462]
I noticed that all the examples and docs reference the `botToken` but do not use any references to the `clientId` and `clientSecret`.  I am not an expert by any means of the Discord APIs but is there a way to use kord without requiring a bot token?

**Comment by DRSchlaubi** [comment]
Client I'd and client secret are required for the oauth API which is not supported by Kord as of right now. The only thing not requiring a bot token are webhooks, but I don't know what you want to do so I cannot fully answer your question

**Comment by dotCipher** [comment]
@DRSchlaubi :  I am mainly only looking to just authenticate with my client ID and client secret and read messages from discord via API (stream them via web socket possibly?)

Is that on the roadmap for Kord?

**Comment by DRSchlaubi** [comment]
Websocket API is for bots only

**Comment by dotCipher** [comment]
Gotcha ok so to stream messages I would need to have a bot anyway?

**Comment by DRSchlaubi** [comment]
Yes

**Comment by dotCipher** [comment]
Ok, I guess then that solves my problem but I would still be curious about if using client ID and client secret is on the road map for kord?

**Comment by DRSchlaubi** [comment]
I am not aware of any plans on supporting the OAuth API, supporting the bot api is work enough for now and the OAuth API is quite different.

For clarification: it's not like you can log in to the API this library currently supports as a Discord user, most of this libraries features are only available for bots, the user API pretty much can just add users to servers and retrieve information about the user

**Comment by DRSchlaubi** [comment]
Gonna close this for now, we might revisit it at some point but not yet
