### ISSUE TITLE
Support for auditory log limit parameter

### ISSUE THREAD

**Issue by misterquestions** [kordlib/kord#476]
Hey there.

I'm opening this issue as a request to add the limit parameter to the get audit log request. Rather than using a default value. 

Also I attach the documentation link that shows the property I'm talking about.

https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log

Hope someone can add it!
Thanks in advance.

**Comment by DRSchlaubi** [comment]
That parameter is already implemented?
https://github.com/kordlib/kord/blob/555e31b04ccb7306e5d873c10a2c7a98374184b4/rest/src/main/kotlin/json/request/AuditLogRequests.kt#L10

Am I missing something here?

**Comment by DRSchlaubi** [comment]
Okay the builder misses it
