### ISSUE TITLE
Missing StringBuilder in OptionsBuilder

### ISSUE THREAD

**Issue by Glennmen** [kordlib/kord#496]
For every type there is a builder except for String.
And OptionsBuilder itself being a sealed class I cannot use this to quickly add the string option.

I want to add a required string parameter but am not able to find any examples.

**Comment by HopeBaron** [comment]
You are looking for StringChoiceBuilder

**Comment by Glennmen** [comment]
@HopeBaron I don't think that is what I am looking for, I do not want to add choices but a string input.

I was able to do it like this but it took me way to long to find it without docs/examples.
```kotlin
guild.createChatInputCommand("code", "Convert an Android redeem code into an iOS link") {
            string("redeem_code", "The Android redeem code") {
                required = true
            }
        }
```

**Comment by HopeBaron** [comment]
string has a `choice` function in it's DSL; you didn't give much information about what you are trying to do :thinking:

**Comment by Glennmen** [comment]
Maybe what I am using is wrong but it works 😅 
I am/was looking how to add a required string input (not choices).

**Comment by HopeBaron** [comment]
Feel free to re-open the issue to followup on the topic
