### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by Glennmen** [kordlib/kord#498]
Hi,

I was able to get it running locally in IntelliJ but this is currently with my Discord token hardcoded.
I am not able to find how to get the token from properties into the compiled jar file.

Also are there any best practices on how to deploy this to a server?
Possibly with Github Actions.

**Comment by HopeBaron** [comment]
Hi glenn, you may be interested in reading on docker and environment variables to put the token somewhere safe;

We don't have any recommended deployment procedures at the time being; you are free to deploy your bot the way you want and need.

**Comment by DRSchlaubi** [comment]
As hope said there is no official recommendation, but I use my own [envconf](https://github.com/DRSchlaubi/envconf) library, allowing me to create a Config class like this
```kotlin
object Config {
  val TOKEN by environment
}
```

Then I make a Dockerimage 
```Dockerfile
FROM ibm-semeru-runtimes:open-17-jre-focal

WORKDIR /usr/app
COPY build/install/mikmusic ./

LABEL org.opencontainers.image.source = "https://github.com/DRSchlaubi/mikmusic"

ENTRYPOINT ["bin/mikmusic"]
```

Relevant CI script: https://github.com/DRSchlaubi/mikbot/blob/db92e2e978ec1828ae40b37f7d097dafac66107a/.github/workflows/ci.yaml#L42-L70

And the following docker-compose file: https://github.com/DRSchlaubi/mikbot/blob/db92e2e978ec1828ae40b37f7d097dafac66107a/docker-compose.yml#L11-L14

Then you can simply make a .env file like this
```
TOKEN=21345643
```

**Comment by Glennmen** [comment]
@DRSchlaubi Thank you very much! I will try to make some time tomorrow and try this out.

**Comment by HopeBaron** [comment]
Feel free to re-open the issue to followup on the topic
