### ISSUE TITLE
Add modal interaction callback type

### ISSUE THREAD

**Issue by valentinegb** [kordlib/kord#527]
Modals were documented by Discord in this commit: [4b6c6a1](https://github.com/discord/discord-api-docs/commit/4b6c6a14d46ff2e62f6384e3ebd9116243c650c9)

**Comment by Lukellmann** [comment]
@MrPowerGamerBR is working on it

**Comment by Lukellmann** [comment]
now in #531

**Comment by Lukellmann** [comment]
The latest release, version `0.8.x-M10`, added support for modals, this can be closed.
