### ISSUE TITLE
Fix typos in wiki

### ISSUE THREAD

**Issue by daymxn** [kordlib/kord#542]
Nit, but under [behaviors in the wiki](https://github.com/kordlib/kord/wiki/Entities#behaviors), I realized there's a small typo on the `MessageCreateEvent` in the code blocks. For example, the first code block:

```kotlin
kord.on<MessageCreatEvent> {
    if(message.content == "!ping") return@on

    TODO("respond")
}
```

Should instead be:

```kotlin
kord.on<MessageCreateEvent> {
    if(message.content == "!ping") return@on

    TODO("respond")
}
```

**Comment by HopeBaron** [comment]
Done
