### ISSUE TITLE
LinearRetry is not linear between start and finish

### ISSUE THREAD

**Issue by ToxicMushroom** [kordlib/kord#596]
I assume linear retry should go like this:
![image](https://user-images.githubusercontent.com/32853531/163674060-848e36a3-1067-4e5a-a10e-eb97daeec173.png)

**Case maxTries = 1, what duration should the delay be**
Unsure what the correct behaviour would be (e.g. firstBackOff or maxBackOff or the median between them ?)
Currently it is delay(maxBackOff-firstBackOff)

**Case maxTries = Int.MAX_VALUE**
It should probably the start at firstBackOff and progress linearly towards maxBackOff so that Int.MAX_VALUE increments were done to the delay to get there.
-> currently it starts at 0ms 

You can replicate this behaviour with the following code
```kotlin
    val retrier = LinearRetry(1.seconds,  60.seconds, Int.MAX_VALUE)
    runBlocking {
        while(retrier.hasNext) {
            retrier.retry()
            println(System.currentTimeMillis())
        }
    }
```

**Comment by Lukellmann** [comment]
Yeah, this seems wrong.
I think we should simply forbid maxTries = 1.
And for maxTries = Int.MAX_VALUE I agree.

Do you think you could contribute a fix yourself?

**Comment by ToxicMushroom** [comment]
yes
