### ISSUE TITLE
Discord bot stopped working after update to 8.0-M14 from 8.0.M2

### ISSUE THREAD

**Issue by zayats1** [kordlib/kord#612]
![image](https://user-images.githubusercontent.com/40402186/170879602-fabbe0f7-9412-4e35-b9ab-c1327d6fdd51.png)

![image](https://user-images.githubusercontent.com/40402186/170879688-ec6e5f67-384a-4a73-9e41-82d542304475.png)
![image](https://user-images.githubusercontent.com/40402186/170879702-572ba3c3-6198-4c91-b2cb-569317fc0184.png)
![image](https://user-images.githubusercontent.com/40402186/170879753-f3658aa1-454f-4069-b3ea-16493480c27d.png)
![image](https://user-images.githubusercontent.com/40402186/170879779-69d1640f-7b37-4ada-be15-35e2677f6156.png)

**Comment by Lukellmann** [comment]
You probably need to enable the message content intent.

**Comment by zayats1** [comment]
how?

**Comment by Lukellmann** [comment]
```kotlin
kord.login {
    @OptIn(PrivilegedIntent::class)
    intents += Intent.MessageContent
}
```

**Comment by Lukellmann** [comment]
You also need to enable it in the Bot section of your App in the Developer Portal.

**Comment by zayats1** [comment]
thank you.
