### ISSUE TITLE
Connection to VoiceGateway websocket throws HTTP 400 Error

### ISSUE THREAD

**Issue by sebampuero** [kordlib/kord#613]
Whenever using `voiceChannel?.connect{}` the following is thrown:

`[DefaultDispatcher-worker-13] ERROR dev.kord.voice.gateway.DefaultVoiceGateway - No transformation found: class io.ktor.utils.io.ByteBufferChannel (Kotlin reflection is not available) -> class io.ktor.client.plugins.websocket.DefaultClientWebSocketSession (Kotlin reflection is not available)
with response from wss://russia3325.discord.media?v=4:
status: 400 Bad Request
response headers: 
Server: cloudflare
, Date: Fri, 03 Jun 2022 16:06:53 GMT
, Content-Type: text/html
, Content-Length: 155
, Connection: close
, CF-RAY: -`

The bot enters the voice channel , but it does not send any voice data when using an AudioProvider

**Comment by lost-illusi0n** [comment]
#626 has been merged and should solve this. This can be closed.
