### ISSUE TITLE
4014 Disallowed intent(s) with MessageCreateEvent

### ISSUE THREAD

**Issue by Doomsdayrs** [kordlib/kord#620]
This is caused by line 474 of Util.kt requiring MessageContent to be allowed

```
    MessageCreateEvent::class, MessageUpdateEvent::class -> {
        +GuildMessages
        +DirectMessages
        +MessageContent
    }
```

Can this requirement be dropped?

**Comment by Lukellmann** [comment]
You can enable the `GuildMessages` and `DirectMessages` Intents separately instead.

**Comment by Doomsdayrs** [comment]
> You can enable the `GuildMessages` and `DirectMessages` Intents separately instead.

I cannot, this is automatically done when trying to register MessageCreateEvent flow collection.

**Comment by Lukellmann** [comment]
[Here](https://github.com/kordlib/kord/blob/0.8.x/core/src/main/kotlin/Kord.kt#L608) is the code for `on`, it doesn't do anything with intents.
Intents are specified in the `login` function.

**Comment by HopeBaron** [comment]
This issue has been closed; please reopen if you want to discuss further
