### ISSUE TITLE
New Release to Support Kotlin 1.7

### ISSUE THREAD

**Issue by DarkAtra** [kordlib/kord#623]
Hey, i wanted to upgrade to Kotlin 1.7 but the latest version of this lib doesn't seem compatible due to changes to the `TimeMark` interface. Is there any chance that you could release a new version featuring the changes that are already on the main branch?

**Comment by NoComment1105** [comment]
Kord has been updated as of [this commit](https://github.com/kordlib/kord/commit/7d6782f1f1853bd7399675f9d364f9de4191e30e). To use it, use `0.8.x-SNAPSHOT` in your körd version

**Comment by DarkAtra** [comment]
just out of curiosity: what's stopping you from releasing it as a non snapshot version?

**Comment by HopeBaron** [comment]
We have migrated from Ktor 1.x to 2.x which caused notable connection issues. We need to properly fix these before a release.

**Comment by DarkAtra** [comment]
makes sense, i'll stick with kotlin 1.6.x for now
