### ISSUE TITLE
Properly implement login rate limiting

### ISSUE THREAD

**Issue by DRSchlaubi** [kordlib/kord#625]
Currently we connect all shards at once and rate limit the identify command, which causes session resets and timeouts (see #624)

A better solution would be to implement rate limiting for logins

**Comment by Lukellmann** [comment]
You mean taking into account [`session_start_limit`](https://discord.com/developers/docs/topics/gateway#get-gateway-bot) (most importantly `max_concurrency`) like described in [Sharding](https://discord.com/developers/docs/topics/gateway#sharding), right?

**Comment by DRSchlaubi** [comment]
Yes
