### ISSUE TITLE
Kotlin 1.7 fails with TimeMark error

### ISSUE THREAD

**Issue by rawilder** [kordlib/kord#663]
In the kotlin upgrade to 1.7, TimeMark was changed from a class to an interface. 

Here timemark is used as an implementation: https://github.com/kordlib/kord/blob/0.8.x/common/src/main/kotlin/ratelimit/TimeSourceIntervalRateLimiter.kt#L41

My best guess is the compiled versions don't like each other resulting in this error on kotlin 1.7.

```Exception in thread "DefaultDispatcher-worker-4" java.lang.IncompatibleClassChangeError: Found interface kotlin.time.TimeMark, but class was expected```

**Comment by Lukellmann** [comment]
The newest version is on Kotlin 1.7. This should fix this problem.

**Comment by LeadWoods0902** [comment]
> The newest version is on Kotlin 1.7. This should fix this problem.

Is the newest version (as of 08/08/2022) 0.7.4?

**Comment by Lukellmann** [comment]
No, it's `0.8.0-M15`, see [releases](https://github.com/kordlib/kord/releases).

**Comment by Lukellmann** [comment]
iirc think the latest kordex snapshot should be fine

**Comment by DRSchlaubi** [comment]
Closing this as it has been stale for half a year
