### ISSUE TITLE
Slash command responses not working when running bot on a VDS when using embeds

### ISSUE THREAD

**Issue by H4kt** [kordlib/kord#718]
I was just about to host my bot on a VDS when I stumbled upon this strange behavior.

VDS in running on: `Ubuntu 18.04.6 LTS`
Java version used to run the bot: `17.0.1 2021-10-19 LTS`

Here is a piece of code for a command executor:
```kotlin
val response = interaction.deferPublicResponse()

response.respond {
    embed {
        title = ":white_check_mark: Connected"
        description = "Connected to ${channel?.asChannel()?.name}"
        color = Colors.SUCCESS
    }
}
```

This results in an infinite "Bot is thinking message"
![image](https://user-images.githubusercontent.com/50774419/201397184-a26f54d5-2ea2-44c8-ad4f-a500c36ddffb.png)

When I'm running the same code on my PC everything works just fine
![image](https://user-images.githubusercontent.com/50774419/201397374-d65bf695-4717-4af1-be37-f8d35b9e74d4.png)

Removing the embed and sending a plain text response using `content` property works fine on a VDS.

I tried wrapping `response.respond` with a `try-catch` block but no error shows up
I'm wandering what the issue is, because I don't really know how embeds work under the hood

**Comment by HopeBaron** [comment]
Hello

Could you provide logs on trace level?

Check the wiki on how to set it up if you haven't

**Comment by H4kt** [comment]
Stupid me didn't even think of trying to enable trace level.
The issue is not with your library but with my code using AWT Color class to parse hex values for colors.
Sorry for opening this useless issue
