### ISSUE TITLE
Cannot cast ResolvedChannel to MessageChannelBehavior

### ISSUE THREAD

**Issue by DeDiamondPro** [kordlib/kord#736]
I have a slash command and I need to cast a channel argument to `MessageChannelBehavior` to send a message in the channel. However I found an issue while attempting this, casting `ResolvedChannel` to `MessageChannelBehavior` produces a `ClassCastException`. 
```kotlin
arguments.channel as MessageChannelBehavior
```
produces
```kotlin
java.lang.ClassCastException: class dev.kord.core.entity.channel.ResolvedChannel cannot be cast to class dev.kord.core.behavior.channel.MessageChannelBehavior (dev.kord.core.entity.channel.ResolvedChannel and dev.kord.core.behavior.channel.MessageChannelBehavior are in unnamed module of loader 'app')
```
After a bit more digging I found something interesting, calling `.fetchChannel()` on it and attempting to cast it then works as expected. This is probably because fetching the channel goes from a resolved to a normal channel.
```kotlin
arguments.channel.fetchChannel() as MessageChannelBehavior
```

**Comment by Lukellmann** [comment]
The preferred way would be to call `arguments.channel.asChannelOf<TheChannelType>()`, this also uses the cache.

**Comment by DeDiamondPro** [comment]
> The preferred way would be to call `arguments.channel.asChannelOf<TheChannelType>()`, this also uses the cache.

Alright, thank you. That works.
