### ISSUE TITLE
Roadmap to be stable?

### ISSUE THREAD

**Issue by viktorhrekh** [kordlib/kord#767]
**Is there anything specific before Kord is going to be stable?**
**It would be nice to have a roadmap** before stable release, as that way it is easier to track updates and to commit something really NEEDED.
Personally, I would like to commit onto this project, but as there is no any roadmap I have no clue what I could help with.

**Comment by HopeBaron** [comment]
Hello Viktor,
The roadmap is split into issues as of the time being
We need to rewrite parts of the api check #758 to find things that we want to fix before considering Kord to be stable
