### ISSUE TITLE
why unresolved reference?

### ISSUE THREAD

**Issue by AlloMoondragon** [kordlib/kord#809]
I may be somewhat of a noob, but it is unresolvedreferencing and idk why.
![Screenshot_20230406_203137_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/230535894-4c31c401-fcbe-4a51-83c7-751daf3731f4.png)
even tho i imported ALL the stuff and android.content.Intent
![Screenshot_20230406_203039_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/230535968-289b740b-67b1-4c62-9e00-8344da9dc944.png)
Even as a noob I figure out most things ~but not figured out this.  And following the intros exactly doesn't help ~they are what leads to this issue.  This is basically from copypasting the codefrom the intro.
![Screenshot_20230406_203934_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/230536342-5f2b060f-d7e7-4b91-90f7-9dc3e4886395.png)
ignore my having my token on a variable and diff variable name for response.  those shouldn't affect this.  It's basically straight from intro yet unresolved.  I then found every package I possibly could and imported them (would be handy having a pointer to them in the intro).  yet still unresolved.
![Screenshot_20230406_203940_AndroidIDE~2](https://user-images.githubusercontent.com/127817827/230536681-2a48f987-0996-4595-aff0-6c312248d2bb.png)

**Comment by HopeBaron** [comment]
Hello I'm not sure what's wrong; 
Can you share your gradle configuration?

**Comment by DRSchlaubi** [comment]
This sounds like a configuration issue on your side, feel free to join [our discord](https://discord.gg/6jcx5ev) and ask for help there
