### ISSUE TITLE
GuildBehaviour#swapChannelPositions yields a 400 with more than one swap

### ISSUE THREAD

**Issue by Tmpod** [kordlib/kord#827]
When performing multiple swaps using [`GuildBehaviour#swapChannelPositions` ](https://github.com/kordlib/kord/blob/9126cf4b63a439efb5b724d7672525a984ef63ee/core/src/commonMain/kotlin/behavior/GuildBehavior.kt#L853), the API returns 400, saying `"Only one channel can have a parent_id modified at a time"`.

I looked at KtorHttpHandler's debug logs and indeed Kord was sending both `lock_permissions` and `parent_id` as `null` for all channels, which I found odd. Then I looked at the docs and realised they are not documented as optional. After checking the network logs for Discord in my browser, I confirmed they are indeed optional, as the client itself only sends `id` and `position` for every channel when you drag-and-drop them around.

Fixing this will require a change in Discord's own documentation (for which I will open an issue there soon) and a change in Kord's [`ChannelPositionSwapRequest`](https://github.com/kordlib/kord/blob/9126cf4b63a439efb5b724d7672525a984ef63ee/rest/src/commonMain/kotlin/json/request/GuildRequests.kt#L75) (for which I will open a PR soon).

**Comment by lukellmann** [comment]
thanks for the detailed report!
