### ISSUE TITLE
Add permission overwrite for `@everyone`

### ISSUE THREAD

**Issue by LaylaMeower** [kordlib/kord#848]
I couldn't find anything about this in the wiki - I may have accidentally didn't see it - but how would one set the "default" permissions for `@everyone`?

```kotlin
member.guild.createTextChannel(member.username) {
            topic = "Guild-Private DM with ${member.mention} (${member.username} // ${member.id}), created by $botName"
            reason = "$topic because they joined."
            parentId = category.id

            addMemberOverwrite(member.id) {
                allowed += Permission.ViewChannel
            }
        }
```

**Comment by HopeBaron** [comment]
Hello @LaylaMeower 
@everyone has the same ID as the guild
So use the of the guild you want to get the everyone role for.

**Comment by LaylaMeower** [comment]
> Hello @LaylaMeower everyone has the same ID as the guild So use the of the guild you want to get the everyone role for.

Oh ic, thanks!
