### ISSUE TITLE
Guild missing "created at" property

### ISSUE THREAD

**Issue by DelilahEve** [kordlib/kord#862]
As best I can tell, Guild objects are missing the created at property, though I'm not certain this isn't just me missing some detail about the way Kord operates. DiscordPy, Javacord, and others all offer this property on guild objects, but I don't see an equivalent in either `Guild` or `GuildData`.

**Comment by DRSchlaubi** [comment]
You can use [`guild.id.timestamp`](https://dokka.kord.dev/common/dev.kord.common.entity/-snowflake/timestamp.html)
