### ISSUE TITLE
MessageModifyBuilder and MessageCreateBuilder should share a common interface

### ISSUE THREAD

**Issue by daymxn** [kordlib/kord#880]
This should probably apply to nested types as well, but a common interface should be shared between these classes.

While you couldn't share things like `embeds` in the common interface- you *could* share the extension methods. For example:

```kotlin
@KordDsl
public sealed interface MessageBuilder {
    public var content: String?
    public var allowedMentions: AllowedMentionsBuilder?
    public var flags: MessageFlags?
    public var suppressEmbeds: Boolean?

    public fun addFile(name: String, contentProvider: ChannelProvider): NamedFile
}

public inline fun MessageBuilder.embed(block: EmbedBuilder.() -> Unit)

public inline fun MessageBuilder.allowedMentions(block: AllowedMentionsBuilder.() -> Unit = {})

public inline fun MessageBuilder.actionRow(builder: ActionRowBuilder.() -> Unit)

public inline fun MessageBuilder.messageFlags(builder: MessageFlags.Builder.() -> Unit)
```

This would allow consumers to follow more DRY principles in their extensions; as you could define an extension under the common interface instead of creating two separate (duplicate) extension methods.

Ideally, you would create a `sealed` hierarchy, such that you could do things like this:

```kotlin
public inline fun MessageBuilder.embed(block: EmbedBuilder.() -> Unit) {
    contract { callsInPlace(block, InvocationKind.EXACTLY_ONCE) }

    when(this) {
        is MessageModifyBuilder -> embeds = (embeds ?: mutableListOf()).also {
            it.add(EmbedBuilder().apply(block))
        }
        is MessageCreateBuilder -> embeds.add(EmbedBuilder().apply(block))
    }
}
```

But if you wanted to avoid a breaking change, you could either throw an `Exception` on `else`, or just not do anything if there isn't a return value (bit of a design choice there).

**Comment by lukellmann** [comment]
i started working on this a few weeks ago, you can track my progress on this branch (i'll be force pushing): https://github.com/kordlib/kord/tree/message-builder
