### ISSUE TITLE
Trying to mention the everyone role results in a malformed @@everyone mention in the client

### ISSUE THREAD

**Issue by BartArys** [kordlib/kord#94]
```kotlin
channel.createMessage(guild.everyoneRole.mention)
```

results in:
`@@everyone`

This behaviour on is correct according the official docs, but it seems like the client stumbles over the special everyone type. Using the literal `@everyone` works fine though.

Proposed solution:
Introduce a check on `RoleBehavior#mention` that checks for `guildId.value == id.value` and returns the literal `@everyone` on true instead.

**Comment by HopeBaron** [comment]
sounds like the simplest solution
