### ISSUE TITLE
Intents setting not found

### ISSUE THREAD

**Issue by aoskyred** [kordlib/kord#948]
Hi, I can't use `intents`. Is it deleted or moved to `Kord(key).login` builder?
Error type: Unresolved reference.
Lib version(s): 0.14.0 and 0.13.1
Kotlin version: 1.9.23
Code:
```kotlin
val bot = Kord(Config.key) {
    intents = Intents(Intent.Guilds, Intent.DirectMessages, Intent.GuildMessages)
}
```

Wiki: https://github.com/kordlib/kord/wiki/Intents

**Comment by DRSchlaubi** [comment]
Intents were moved to the login builder

```kotlin
val kord = Kord(token)
kord.login {
  intents {
    +Intents.Guilds
    +Intents.DirectMessages
    +Intents.GuildMessages
  }
}
```
